server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : product-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/product-service/**
        - id: cart-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/cart-service/**