server:
  port: 8045
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

product:
  jms:
    destination: product