server:
  port: 8049

spring:
  application:
    name: cart-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

product:
  jms:
    destination: product

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka